fixtures:
  repositories:
    common:
      repo: 'https://github.com/kodguru/puppet-module-common.git'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    cron:
      repo: 'https://github.com/puppetlabs/puppetlabs-cron_core.git'
    mount:
      repo: 'https://github.com/puppetlabs/puppetlabs-mount_core.git'
    selinux:
      repo: 'https://github.com/puppetlabs/puppetlabs-selinux_core.git'
